config/routes.rb
Rails.application.routes.draw do
  
  get 'metric/index'

  get 'metric/edit'

  get 'metric/delete'

  get 'metric/new'

  resources :pages
  resources :urls
  resources :content_owners
  

end

app/models/campaign_metrics.rb
class CampaignMetrics < ActiveRecord::Base
end

app/models/content_owner.rb
class ContentOwner < ActiveRecord::Base
	has_many :pages
	 has_many :urls, through: :pages
	validates :office, presence: true
end

app/models/metric.rb
class Metric < ActiveRecord::Base
	belongs_to :pages
end

app/models/page.rb
class Page < ActiveRecord::Base
	belongs_to :content_owners
	has_many :urls
end

app/models/url.rb
class Url < ActiveRecord::Base
	belongs_to :page
	validates :campaign_source, :campaign_description,:campaign_medium, presence: true
##def concate_page_url
	##self.page.page_path + "utm_source=" + self.campaign_medium + "utm_source=" + self.campagin_source + "utm_campaign=" + self.campaign_description
##end

def built_url
	my_uri = URI("http://www.gov.gov")
	if page
	my_uri.path = "/" + page.page_path
	else
	puts"nope"

	end
	my_uri.query = URI.encode_www_form({utm_source: self.campaign_source, utm_medium: self.campaign_medium, utm_campaign: self.campaign_medium})
	my_uri.to_s
end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/content_owner_controller.rb
class ContentOwnersController < ApplicationController
  def index
  	@content_owners = Content_owner.all
  end

  def new
  end

  def edit
  end

  def delete
  end

  def url_params
  	params.require(:content_owners).permit(:office)
  end
end

app/controllers/metric_controller.rb
class MetricController < ApplicationController
  def index
  	@metric = Metric.all
  end

  def edit
  end

  def delete
  end
	def create
	  @metric = Metric.new(metric_params)
	  if @metric.save
	  redirect_to page_path(@metric)
	else
	  render 'new'
	end
	end
  def new
  end

    def metric_params
  	params.require(:bounce_rate, :sessions)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@pages = Page.all
  end

  def create
      @page = Page.new(page_params)
      if @page.save
      redirect_to page_path(@page)
    else
      render 'new'
    end
  end

  def new
  	@page = Page.new
    @content_owner = ContentOwner.all 
  end

  def edit
  end

  def delete
  end

  def url_params
    params.require(:page).permit(:content_owner_id, :path, :title)
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
  	@urls = Url.all
  end

  def create
      @url = Url.new(url_params)
      if @url.save
      redirect_to urls_path(@url)
    else
      render 'new'
    end
  end

  def new
  	@url = Url.new
    @pages = Page.all 
  end

  def edit
  end

  def delete
  end

  def success

  end

  def url_params
    params.require(:url).permit(:campaign_source, :campaign_description,:campaign_medium, :page_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_owner_helper.rb
module ContentOwnerHelper
end

app/helpers/metric_helper.rb
module MetricHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/content_owner/new.html.erb
<h1>ContentOwner#new</h1>
<p>Find me in app/views/content_owner/new.html.erb</p>

app/views/content_owners/delete.html.erb
<h1>ContentOwner#delete</h1>
<p>Find me in app/views/content_owner/delete.html.erb</p>

app/views/content_owners/edit.html.erb
<h1>ContentOwner#edit</h1>
<p>Find me in app/views/content_owner/edit.html.erb</p>

app/views/content_owners/index.html.erb
<h1>ContentOwner#index</h1>
<p>Find me in app/views/content_owner/index.html.erb</p>

app/views/content_owners/new.html.erb
<%# For the Content Owners%>
<h1>New URL</h1>

	<% if @page.errors.any? %>
	<h1>  Please check to make sure all fields are entered </h1>
		<ul>
<% @page.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
<% end %>


</ul>

<%= form_for(@page) do |f| %>
	<p>
	  <select name="page[conent_owners_id]">
      <% @content_owner.each do |conent_owner| %>
        <option value="<%= conent_owners.id %>"><%= conent_owners.office %> </option>
      <% end %>
    </select>
	</p>

	<p>
	<%= f.label :page_path %>
	<%= f.text_field :page_path %>
	</p>

	<p>
	<%= f.label :page_title%>
	<%= f.text_field :page_title%>
	</p>


	<%= f.submit "Submit"%>
	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlutonicBot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/metric/delete.html.erb
<h1>Metric#delete</h1>
<p>Find me in app/views/metric/delete.html.erb</p>

app/views/metric/edit.html.erb
<h1>Metric#edit</h1>
<p>Find me in app/views/metric/edit.html.erb</p>

app/views/metric/index.html.erb
<h1>Metric#index</h1>
<p>Find me in app/views/metric/index.html.erb</p>

app/views/metric/new.html.erb
<h1>Metric#new</h1>
<p>Find me in app/views/metric/new.html.erb</p>

app/views/pages/delete.html.erb
<h1>Page#delete</h1>
<p>Find me in app/views/page/delete.html.erb</p>

app/views/pages/edit.html.erb
<h1>Page#edit</h1>
<p>Find me in app/views/page/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Path</th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.page_title %></td>
        <td><%= page.page_path %></td>
      
        <
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'new page', new_page_path %>

app/views/pages/new.html.erb
<%# Page For the thing %>
<h1>New Page</h1>

	<% if @page.errors.any? %>
	<h1>  Please check to make sure all fields are entered </h1>
		<ul>
<% @page.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
<% end %>


</ul>

<%= form_for(@page) do |f| %>
	<p>
	  <select name="page[conent_owners_id]">
      <% @content_owner.each do |conent_owner| %>
        <option value="<%= conent_owner.id %>"><%= conent_owner.office %> </option>
      <% end %>
    </select>
	</p>

	<p>
	<%= f.label :page_path %>
	<%= f.text_field :page_path %>
	</p>

	<p>
	<%= f.label :page_title%>
	<%= f.text_field :page_title%>
	</p>


	<%= f.submit "Submit"%>
	
<% end %>

app/views/urls/delete.html.erb
<h1>Url#delete</h1>
<p>Find me in app/views/url/delete.html.erb</p>

app/views/urls/edit.html.erb
<h1>Url#edit</h1>
<p>Find me in app/views/url/edit.html.erb</p>

app/views/urls/index.html.erb
<h1>All Campagins</h1>
<table>
<thead>
    <tr>
      <th>Campaign Name</th>
      <th>Campaign Source</th>
      <th>Campaign Medium</th>
      <th>Full URL</th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.campaign_description %></td>
        <td><%= url.campaign_source %></td>
        <td><%= url.campaign_medium %></td>
        <td><%= url.built_url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/urls/new.html.erb
##urls

<h1>New URL</h1>

	<% if @url.errors.any? %>
	<h1>  Please check to make sure all fields are entered </h1>
		<ul>
<% @url.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
<% end %>
</ul>

<%= form_for(@url) do |f| %>
	<p>
	  <select name="url[page_id]">
      <% @pages.each do |page| %>
        <option value="<%= page.id %>"><%= page.page_title %>, <%=page.page_path %> </option>
      <% end %>
    </select>
	</p>

	<p>
	<%= f.label :campaign_source %>
	<%= f.text_field :campaign_description %>
	</p>

	<p>
	<%= f.label :campaign_source%>
	<%= f.text_field :campaign_source %>
	</p>

	<p>
	<%= f.label :campaign_medium %>
	<%= f.text_field :campaign_medium %>
	</p>


	<%= f.submit "Submit"%>
	
<% end %>